#!/usr/bin/python3
#SPDX-FileCopyrightText: 2025 Masaki Yoshikawa<j2370rgg@sit.ac.jp>x
#SPDX-License-Identifier: BSD-3-Clause

import sysxy

ans = 0

for line in sys.stdin:
	try:
		ans += int(line)
	except:
		ans += float(line)

print(ans)
